### ISSUE TITLE
MP4Box.createFile is not a function

### ISSUE THREAD

**Issue by douglassllc** [gpac/mp4box.js#158]
Receiving the following error when attempting to run info.js node under test directory.

```
var mp4boxfile = MP4Box.createFile();
                        ^

TypeError: MP4Box.createFile is not a function
    at Object.<anonymous> (/var/www/html/test/tmp/mp4box.js/test/node/fragment.js:11:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by JuanIrache** [comment]
Getting the same error with the example provided on the main page, but I have seen this in other examples and it works. Not sure what the difference is in terms of behaviour.

```
var MP4Box = require('mp4box').MP4Box;
var mp4boxfile = new MP4Box(false);
```

**Comment by cconcolato** [comment]
This is due to a mismatch of versions. Previous versions of mp4box.js used the `new MP4Box` syntax. The latest uses the `createFile` syntax. Make sure you are using matching versions between info.js and mp4box.js. Note that the npm package is up to date now and uses the createFile syntax. Reopen if not clear.

**Comment by douglassllc** [comment]
@cconcolato thank you for your response. all better now.
