### ISSUE TITLE
Fails to load AVIF with invalid `property_index` in `ItemPropertyAssociationBox` (`ipma`)

### ISSUE THREAD

**Issue by baumanj** [gpac/mp4box.js#238]
When clicking `Load` with [the attached file](https://github.com/gpac/mp4box.js/files/6526888/ipma-invalid-property-index.avif.zip), the button becomes disabled, but no progress is registered.

Console output:
```
[0:00:09.216] [ISOFile] Processing buffer (fileStart: 0) mp4box.all.js:34:14
[0:00:09.216] [MultiBufferStream] Appending new buffer (fileStart: 0 - Length: 294) mp4box.all.js:26:14
[0:00:09.217] [MultiBufferStream] 1 stored buffer(s) (0/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.217] [MultiBufferStream] Stream ready for parsing mp4box.all.js:26:14
[0:00:09.218] [MultiBufferStream] 1 stored buffer(s) (0/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.218] [MultiBufferStream] Found position in existing buffer #0 mp4box.all.js:26:14
[0:00:09.219] [MultiBufferStream] Repositioning parser at buffer position: 0 mp4box.all.js:26:14
[0:00:09.220] [BoxParser] Found box of type 'ftyp' and size 32 at position 0 mp4box.all.js:26:14
[0:00:09.220] [MultiBufferStream] 1 stored buffer(s) (32/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.221] [BoxParser] Found box of type 'meta' and size 229 at position 32 mp4box.all.js:26:14
[0:00:09.221] [BoxParser] 'meta' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.222] [BoxParser] Found box of type 'hdlr' and size 33 at position 44 mp4box.all.js:26:14
[0:00:09.222] [BoxParser] Found box of type 'pitm' and size 14 at position 77 mp4box.all.js:26:14
[0:00:09.223] [BoxParser] 'pitm' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.223] [BoxParser] Found box of type 'iloc' and size 30 at position 91 mp4box.all.js:26:14
[0:00:09.223] [BoxParser] 'iloc' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.223] [BoxParser] Found box of type 'iinf' and size 37 at position 121 mp4box.all.js:26:14
[0:00:09.223] [BoxParser] 'iinf' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.223] [BoxParser] Found box of type 'infe' and size 21 at position 137 mp4box.all.js:26:14
[0:00:09.224] [BoxParser] 'infe' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.225] [BoxParser] Found box of type 'iprp' and size 103 at position 158 mp4box.all.js:26:14
[0:00:09.225] [BoxParser] Found box of type 'ipco' and size 72 at position 166 mp4box.all.js:26:14
[0:00:09.225] [BoxParser] Found box of type 'ispe' and size 20 at position 174 mp4box.all.js:26:14
[0:00:09.226] [BoxParser] 'ispe' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.226] [BoxParser] Found box of type 'pixi' and size 16 at position 194 mp4box.all.js:26:14
[0:00:09.226] [BoxParser] 'pixi' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.226] [BoxParser] Found box of type 'pasp' and size 16 at position 210 mp4box.all.js:26:14
[0:00:09.227] [BoxParser] 'pasp' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.227] [BoxParser] Found box of type 'av1C' and size 12 at position 226 mp4box.all.js:26:14
[0:00:09.227] [BoxParser] 'av1C' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.227] [BoxParser] Found box of type 'ipma' and size 23 at position 238 mp4box.all.js:26:14
[0:00:09.227] [BoxParser] 'ipma' box writing not yet implemented, keeping unparsed data in memory for later write mp4box.all.js:34:14
[0:00:09.227] [MultiBufferStream] 1 stored buffer(s) (261/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.228] [BoxParser] Found box of type 'mdat' and size 33 at position 261 mp4box.all.js:26:14
[0:00:09.228] [MultiBufferStream] Found position in existing buffer #0 mp4box.all.js:26:14
[0:00:09.228] [MultiBufferStream] Repositioning parser at buffer position: 294 mp4box.all.js:26:14
[0:00:09.229] [MultiBufferStream] 1 stored buffer(s) (269/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.229] [MultiBufferStream] 1 stored buffer(s) (294/294 bytes), continuous ranges: [0-293] mp4box.all.js:26:14
[0:00:09.229] [BoxParser] Not enough data in stream to parse the type and size of the box mp4box.all.js:26:14
Uncaught TypeError: can't access property "type", propbox is undefined
    flattenItemInfo https://gpac.github.io/mp4box.js/dist/mp4box.all.js:7624
    appendBuffer https://gpac.github.io/mp4box.js/dist/mp4box.all.js:6176
    onparsedbuffer https://gpac.github.io/mp4box.js/test/ui-helper.js:143
    onBlockRead https://gpac.github.io/mp4box.js/test/ui-helper.js:148
    readBlock https://gpac.github.io/mp4box.js/test/ui-helper.js:170
    parseFile https://gpac.github.io/mp4box.js/test/ui-helper.js:174
    loadHandler https://gpac.github.io/mp4box.js/test/ui-helper.js:214
    createLoadBar https://gpac.github.io/mp4box.js/test/ui-helper.js:118
    onload https://gpac.github.io/mp4box.js/test/filereader.js:356
    EventHandlerNonNull* https://gpac.github.io/mp4box.js/test/filereader.js:354
```

**Comment by baumanj** [comment]
See also https://github.com/gpac/ComplianceWarden/issues/27
