### ISSUE TITLE
Error on "require": RangeError: byteOffset out of range. 

### ISSUE THREAD

**Issue by sjames1958gm** [gpac/mp4box.js#62]
When running in nodejs 0.10.35 I get the following error when running info.js test.
RangeError: byteOffset out of range.
    at Object.defineProperty.set (/home/nzos/Development/node-nzape/node_modules/mp4box/dist/mp4box.all.js:382:24)
    at Object.DataStream (/home/nzos/Development/node-nzape/node_modules/mp4box/dist/mp4box.all.js:272:17)
    at Object.<anonymous> (/home/nzos/Development/node-nzape/node_modules/mp4box/dist/mp4box.all.js:1554:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nzos/Development/node-nzape/info.js:2:20)

mp4box@0.3.8 node_modules/mp4box

**Comment by cconcolato** [comment]
I can reproduce the problem with node v0.10.25 (on Ubuntu), but not with node v0.12.2 (on Windows). Can you try updating your node version?

**Comment by sjames1958gm** [comment]
I downloaded 0.12.0 and it does not get this error.

**Comment by sureshmurali** [comment]
Still I get the same error in node version 0.10.0, 0.12.0, 6.9.1  (Amazon linux) 



> RangeError: byteOffset out of range.
>     at Object.defineProperty.set (/kosen/node_modules/mp4box/dist/mp4box.all.js:382:24)
>     at Object.DataStream (/kosen/node_modules/mp4box/dist/mp4box.all.js:272:17)
>     at Object.<anonymous> (/kosen/node_modules/mp4box/dist/mp4box.all.js:1554:31)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/kosen/routes/video_upload.js:18:20)
