### ISSUE TITLE
Usage with node.js

### ISSUE THREAD

**Issue by SerhanGul** [gpac/mp4box.js#91]
Hi, My node.js version is 4.4.5.. I'm trying to run the node.js examples given under `test/node` but I get the following error message:

```
$ node info.js test.mp4
module.js:327
    throw err;
    ^

Error: Cannot find module 'mp4box'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/guel/projects/mp4box.js/test/node/info.js:2:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I also get the same error for the other examples. What should I do so that the mp4box module is found? I don't have much experience with node.js so I would appreciate any help.

**Comment by cconcolato** [comment]
With node, when using `require`, node tries to load JS file either because the full path is provided or because it is pre-installed on the system. So either you modify the example code to point to the compiled mp4box.all.js file like `require('../dist/mp4box.all.js')` or you install mp4box with npm: `npm install mp4box.js`.
HTH

**Comment by SerhanGul** [comment]
This solved my problem. Thank you very much.
